### ISSUE TITLE
Cities missing isochrones

### ISSUE THREAD

**Issue by maphew** [pkerpedjiev/roadway_routing#2]
Very cool project, thanks for writing and sharing!

There are cities in the list that don't produce isochrones (e.g. http://emptypipes.org/supp/isochrone_driving/whitehorse/ ). Did they work at some point but now have stopped? Or are we looking at no source data available for X? (in which case, maybe remove from list)

Also, the "The origin of this map is described in slightly more detail in the original blog post." link in each city page is broken.

**Comment by pkerpedjiev** [comment]
Wow, thank you for pointing this out! I fixed the original post link and took Whitehorse off the list. I'm not sure why it's not working. Probably never worked and I didn't notice.
